V0:
  config_ver: 0
  model: MultiDAE
  data_path: /data/ephemeral/data/train/
  model_save_path: /data/ephemeral/level2-movierecommendation-recsys-04/code/Autoencoders/saved/
  submit_path: /data/ephemeral/level2-movierecommendation-recsys-04/code/Autoencoders/submit/
  seed: 42
  parameters:
    epochs: 20
    batch_size: 500
    lr: 1e-4
    wd: 0.00
    total_anneal_steps: 200000
    anneal_cap: 0.2
    log_interval: 100
    p_dims:
      - 200
      - 600
    dropout: 0.5
V1:
  config_ver: 1
  model: MultiDAE
  data_path: /data/ephemeral/data/train/
  model_save_path: /data/ephemeral/level2-movierecommendation-recsys-04/code/Autoencoders/saved/
  submit_path: /data/ephemeral/level2-movierecommendation-recsys-04/code/Autoencoders/submit/
  seed: 42
  parameters:
    epochs: 20
    batch_size: 500
    lr: 1e-4
    wd: 0.00
    total_anneal_steps: 200000
    anneal_cap: 0.2
    log_interval: 100
    p_dims:
      - 600
      - 1800
    dropout: 0.5